---
title: "सुलक्षण कीर्ति क्याम्पसको संक्षिप्त चिनारी"


Output: pdf_document
  
site: distill:distill_website



---
<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


```

**क्याम्पस परिचय**\
बौद्ध ज्ञान–विज्ञान, दिगो शान्ति, दिगो विकास, कानुन, शिक्षा–शिक्षण, सामाजिक, राजनीतिक, आर्थिक अध्ययन र सोसँग सम्बन्धित अन्य वातावरणीय ज्ञान–विज्ञानका विधाहरूमा विश्वविद्यालय तहको अध्ययन–अनुसन्धान गर्ने प्राज्ञिक निकायको रुपमा यस सुलक्षण कीर्ति क्याम्पसको स्थापना गरिएको छ ।

लुम्बिनी बौद्ध विश्वविद्यालय र सुलक्षण कीर्ति विहारबीच बि.स. २०७७ साल फागुन २५ गते भएको शैक्षिक सहकार्यको सम्झौताबमोजिम जनस्तर र सहभागिताबाट सञ्चालित मुनाफारहित सामुदायिक–सामाजिक साझेदारी मोडेलमा यसको गठन र सञ्चालन हुँदै आएको छ । 

यो सुलक्षण कीर्ति क्याम्पस नेपालको प्रचलित कानुनअनुसार लुम्बिनी बौद्ध विश्वविद्यालय ऐन, विश्वविद्यालय अनुदान आयोग ऐन तथा नेपाल पब्लिक क्याम्पस संघको सामुदायिक क्याम्पस स्थापना सम्बन्धी व्यवस्थाहरूको अनुसरण गरी लुम्बिनी बौद्ध विश्वविद्यालय र सुलक्षण कीर्ति क्याम्पस सञ्चालक समितिले अनुमोदन गरेको क्याम्पस नियमावली, शैक्षिक प्रशासन विनियम, शिक्षक-कर्मचारी विनियम, आर्थिक विनियम एवं समय समयमा सञ्चालक समितिको बैठकबाट पारित निर्णयहरु बमोजिम सञ्चालन, व्यवस्थापन तथा रेखदेख हुनेछ ।  



**क्याम्पसको अवस्थिति **\
यस क्याम्पसको केन्द्रीय कार्यालय तथा अनुसन्धान केन्द्र काठमाडौं जिल्लाको कीर्तिपुर नगरपालिका, वडा ६, सुन्दरीघाटस्थित सुलक्षण कीर्ति विहारको प्रांगणमा रहेको छ । सम्बन्धित सरोकारवालाहरूसँगको सहकार्य र साझेदारीमा काठमाडौं उपत्यकाका विभिन्न लक्षित स्थानहरूमा समेत क्याम्पसका शैक्षिक तथा अनुसन्धानात्मक सेवा तथा कार्यक्रमहरू विस्तारित गर्न सकिनेछ । 


**सुलक्षण कीर्ति क्याम्पसको मूल आदर्श **\
हामी सबै व्यक्ति, परिवार, समुदाय र राष्ट्रको भौतिक, आर्थिक, सामाजिक, राजनीतिक तथा आत्मिक सुख, खुसी र सम्पन्नता सहितको दिगो शान्ति, सुशासन, न्याय र विकासको साझा लक्ष्यमा पुग्न टेवा पुर्याउन स्वयं यो सुलक्षण कीर्ति क्याम्पस भौतिक, आर्थिक, शैक्षिक, अनुसन्धान र व्यवस्थापनको हिसाबले सक्षम, गुणस्तरीय, दिगो, जिम्मेवार, असल, कुशल र गतिशील ढङ्गले निरन्तर नेतृत्व दिन सक्ने अब्बल र नमुना प्राज्ञिक निकाय बन्ने प्रमुख ध्ययका साथ; 

बौद्ध धर्म, दर्शन, ज्ञान–विज्ञान, ध्यान र नैतिक म्ूाल्य मान्यतामा आधारित शिक्षा, उद्यमकला, क्षमता एवं सीपमार्फत शारीरिक तथा मानसिक स्वस्थता, सम–न्याय, स्वतन्त्रता, समानता, एकता, सम्पन्नता, खुशी, सकरात्मक सोंच, प्रवृत्ति र व्यवहारले युक्त अर्थपूर्ण दिगो शान्ति, सुशासन, न्याय र विकास सहितको मानव जीवन–पद्धति र सभ्यता स्थापनामा योगदान पुर्याउने । 

**उद्देश्यहरू **\
(क) यो क्याम्पसको पहिलो र प्राथमिक काम तथा उद्देश्य लुम्बिनी बौद्ध विश्वविद्यालय र सुलक्षण कीर्ति विहारबीच भएको शैक्षिक सहकार्यको सम्झौता बमोजिम मास्टर इन बुद्धिजम एण्ड सस्टेनेवल डेभलपमेन्ट (Master in Buddhism and Sustainable Development - MBSD) कार्यक्रमलाई प्रभावकारी रुपमा सञ्चालन गर्ने ।\
(ख) लुम्बिनी बौद्ध विश्वविद्यालयसँगको सहकार्यमा कानुन, शिक्षा–शिक्षण, सामाजिक, राजनीतिक तथा आर्थिक अध्ययन एवं बौद्ध चिन्तनका अन्य शैक्षिक एवं अनुसन्धात्मक कार्यक्रमहरुसमेत स्नातक, स्नातकोत्तर, दर्शनाचार्य तथा विद्यावारिधि तहमा सञ्चालन गर्ने । \
(ग) लुम्बिनी बौद्ध विश्वविद्यालयसँगको शैक्षिक सहकार्यको  सम्बन्धलाई थप प्रभावकारी विश्वासिलो, विस्तारित र दिगो बनाउँदै लुम्बिनी बौद्ध विश्वविद्यालयको शैक्षिक अनुसन्धानात्मक तथा समग्र प्रा ज्ञिक उन्नयनमा सहयोग पुर्याउने ।\
(घ) लुम्बिनी सभ्यता र बागमति सभ्यताको समायोजनमा सरोकारावालाहरूको सहकार्यमा काठमाडौं उपत्यकाको दिगो विकासको चुनौतीहरूलाई पहिचान गरी सामाजिक, आर्थिक, वातावरणीय न्याय, सुशासन र सन्तुलन सहितको सुसंस्कृत काठमाडौं तथा बागमति सभ्यता निर्माणमा सहयोगपुर्याउने मुलभुत उद्देश्य रहेको छ ।
